<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Crate\\' => array($vendorDir . '/crate/crate-pdo/src'),
);
