<?php
/**
 * Created by PhpStorm.
 * User: Jim FAN
 * Date: 2017/6/17
 * Time: 16:00
 */

namespace app\mobile\controller;
use think\Controller;

class Base extends  controller
{
    /*
     * 初始化
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}