<?php
/**
 * Created by PhpStorm.
 * User: Jim FAN
 * Date: 2017/6/2
 * Time: 15:20
 * 子账户管理
 *
 */
namespace app\admin\controller;
use app\admin\controller\Base;
class Admin extends Base{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->isLogin();
    }

    /**
     * 子账户列表
     */
    public function adminList(){
        $data['u_parent_id'] = session('admin_auth_id');
        $data = json_decode(forwarding('UserForwarding','\app\Service\users\business\admins','admin_list',data_encode($data)),true);
        $this->assign('list',$data['data']);
        return $this->fetch();
    }

    /**
     * 子账户添加
     */
    public function adminAdd(){
        if($this->request->isPost()){
            $data['u_username'] = $this->request->post('u_username');
            $data['u_nickname'] = $this->request->post('u_nickname');
            $data['u_pwd'] = $this->request->post('u_pwd');
            $data['u_is_enabled'] = $this->request->post('u_is_enabled');
            $data['u_reg_time'] = date('Y-m-d H:i:s',time());
            $data['admin_auth_id'] = session('admin_auth_id');
            $data['u_parent_name'] = session('admin_auth_name');
            $data['u_parent_id'] = session('admin_auth_id');
            $data['u_level'] = session('level');
            return forwarding('UserForwarding','\app\Service\users\business\admins','admin_add',data_encode($data));
        }
        return $this->fetch();
    }

    /**
     * 子账户修改
     * op 0 获取  1 修改
     */
    public function adminEdit(){
        if($this->request->isPost()){
            $data['u_username'] = $this->request->post('u_username');
            $data['u_nickname'] = $this->request->post('u_nickname');
            $data['u_pwd'] = $this->request->post('u_pwd');
            $data['u_is_enabled'] = $this->request->post('u_is_enabled');
            $data['u_admin_id'] = $this->request->post('u_admin_id');
            $data['u_reg_time'] = date('Y-m-d H:i:s',time());
            $data['u_parent_name'] = session('admin_auth_name');
            $data['u_level'] = session('level');
            $data['u_parent_id'] = session('admin_auth_id');
            $data['op'] = 1;      
            return forwarding('UserForwarding','\app\Service\users\business\admins','admin_edit',data_encode($data));
        }else{
            $data['u_admin_id'] = $this->request->get('u_admin_id');
            $data['op'] = 0;
            $res =json_decode(forwarding('UserForwarding','\app\Service\users\business\admins','admin_edit',data_encode($data)),true);
            $this->assign('list',$res['data']);
            return $this->fetch();
        }
    }

    /**
     * 子账户删除
     */
    public function adminRemove(){
        return $this->fetch();
    }

    /**
     * 后台管理员登录
     * @return mixed
     */
    public function Login(){
        return $this->fetch();
    }

}