<?php
/**
 * Created by PhpStorm.
 * User: Jim FAN
 * Date: 2017/5/15
 * Time: 14:25
 */

namespace app\admin\controller;

use think\Cookie;
use think\Log;

class Index extends Base
{
    public function index(){
        $this->isLogin();
        return $this->fetch('index/index');
    }
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function welcome(){
        $this->isLogin();
        $user = session('admin_auth');
        $ip = $this->request->ip();
        $this->assign('ip',$ip);
        $this->assign('now',date('Y-m-d H:i:s'));
        $this->assign('user',$user);
        return $this->fetch('index/welcome');
    }
    /**
     * 管理员登录
     *   'error_code' =>$code,put_data
     *   'data' => $data,
     *   'message'=>$message
     */
    public function login(){
        //用户登录处理
        $data = [];
        if($this->request->isPost()){
            $data['username'] = $this->request->post('username');
            $data['ip'] = $this->request->ip();
            $data['pwd'] = $this->request->post('password');
            $data['verifyCode'] = $this->request->post('verifyCode');
            $data = json_decode(forwarding('UserForwarding','\app\Service\users\business\admins','admin_login',data_encode($data)),true);
            if($data['data']){
                $this->u_control = $this->request->controller();
                $this->u_action = $this->request->action();
                $this->u_client_ip = $this->request->ip();
                $this->adminAddLogs('登录成功',1);
//                return  $this->success('登录成功！',url('index/index'),'',10000);
                return  $this->redirect('index/index');
            }else{
                return  $this->error($data['message'],url('index/login'),'',1);
            }
        }else{
            $content = [
                'title'=>'分分彩后台',
                'description'=>'分分彩后台',
                'keywords'=>'分分彩后台'
            ];
            $this->assign('content',$content);
            return  $this->fetch('/login');
        }
    }



    /**
     * 显示在线用户
     */
    public function numberInfo(){
        $username = session('admin_auth_name');
        if(empty($username)){
            return -3;
        }
        $ip = $this->request->ip();
        $res1 = json_decode(forwarding('lotteryForwarding', '\app\Service\users\business\frontUsers', 'tongjizaixian', ['username'=>$username,'ip'=>$ip]),true);
        $arr = ['u_name'=>session('u_name'),'level'=>session('level')];
        $res = json_decode(forwarding('UserForwarding','\app\Service\users\business\frontUsers','getUserOnline',$arr),true);
        $res['data']['is_another_login'] = empty($res1['data'])?0:$res1['data']['s_client_ip'];//fasle的话没有没有其他人在另一个地方登录
        return $res['data'];
    }
    /**
     * 更改密码
     */
    public function editMima(){
        if($this->request->ispost()){
            $data['name'] = session('admin_auth_name');
            $data['u_username'] = $this->request->post('u_name');
            $data['u_password'] = $this->request->post('u_password');
            $data['u_pwd']  = $this->request->post('u_pwd');
            $data['u_pwds'] = $this->request->post('u_pwds');
            $data['ip']= $this->request->ip();
            $this->adminAddLogs('用户:'.$data['name'].'修改密码!','1');
            $res = forwarding('UserForwarding','\app\Service\users\business\admins','editMima',$data);
            return  $res;
        }
        return  $this->fetch('index/editMima');
    }
}