<?php
/**
 * Created by PhpStorm.
 * User: Jim FAN
 * Date: 2017/7/4
 * Time: 18:50
 */

namespace app\admin\controller;

use app\admin\controller\Base;
class System extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->isLogin();
    }

    /**
     * 系统初始值设定
     */
    public function Systeminitial(){
        if($this->request->isPost()){
            $data = $this->request->post();
            $res = json_decode(forwarding('lotteryForwarding', '\app\Service\lottery\business\config', 'editSystemConf', $data),true);
            if($res['data']){
                $this->adminAddLogs('执行了系统初始值设定'.json_encode($data).'返回结果：修改成功','1');
                return $this->success('修改成功',url('System/Systeminitial'));
            }else{
                $this->adminAddLogs('执行了系统初始值设定'.json_encode($data).'返回结果：'.$res['message'],'0');
                return $this->error('修改失败'.$res['message'],url('System/Systeminitial'));
            }
        }
        $res = json_decode(forwarding('lotteryForwarding', '\app\Service\lottery\business\config', 'getSystemConf', []),true);
        $this->assign('list',$res['data']);
        return  $this->fetch();
    }

    /**
     *赔率设定
     */
    public function Systemrebate(){
        $lid_list = json_decode(forwarding('lotteryForwarding', '\app\Service\lottery\business\lottery', 'getList', []),true);
        $this->assign('lid_list',$lid_list['data']);
        $lid = $this->request->get('lid');
        $data['lid'] = empty($lid)?2:$lid;
        $this->assign('lid',$data['lid']);
        $res = json_decode(forwarding('lotteryForwarding', '\app\Service\lottery\business\prizes', 'getLotteryRebate', $data),true);
        if($res['data']){
            $this->assign('list',$res['data']);
            return $this->fetch();
        }else{
            return  $this->error('配置有误！',url('index/welcome'));
        }
    }
    /**
     * 赔率修改
     *
     */
    public function editRebate(){
        $data = $this->request->post();
        $res = json_decode(forwarding('lotteryForwarding', '\app\Service\lottery\business\prizes', 'editLotteryRebate', $data),true);
        if($res['data']){
            $this->adminAddLogs('执行了赔率修改'.'返回结果：修改成功','1');
            return $this->success("修改成功",url('System/Systemrebate'));
        }else{
            $this->adminAddLogs('执行了赔率修改'.'返回结果：'.$res['message'],'0');
            return $this->error($res['message'],url('System/Systemrebate'));
        }
    }
    /**
     * 彩种设置
     */
    public function Systemlottery(){
        if($this->request->isPost()){
            $data = $this->request->post();
            $data['ip']=$this->request->ip();
            $res = json_decode(forwarding('lotteryForwarding', '\app\Service\lottery\business\config', 'editLidConf', $data),true);
            if($res['data']){
                $this->adminAddLogs('执行了彩种设置'.'返回结果：修改成功','1');
                return $this->success('修改成功',url('System/Systemlottery'));
            }else{
                $this->adminAddLogs('执行了彩种设置'.'返回结果：'.$res['message'],'0');
                return $this->error('修改失败'.$res['message'],url('System/Systemlottery'));
            }
        }else{
            $lidconf = json_decode(forwarding('lotteryForwarding', '\app\Service\lottery\business\config', 'getLidListConf', []),true);
            $this->assign('list',$lidconf['data']['list']);
            $this->assign('conflist',$lidconf['data']['conf']);
            return $this->fetch();
        }
    }

    /**
     * 封锁值设定
     */
    public function Systemlocks(){
        $lid = $this->request->get('lid');
        $lid = empty($lid)?2:$lid;
        if($this->request->isPost()){
            $data = $this->request->post();
            $data['lid'] = $lid;
            $res = json_decode(forwarding('lotteryForwarding', '\app\Service\lottery\business\methods', 'editLockmethods', $data),true);
            if($res['data']){
                $this->adminAddLogs('执行了封锁值设定'.'返回结果：修改成功','1');
                return $this->success('修改成功',url('System/Systemlocks').'?lid='.$lid);
            }else{
                $this->adminAddLogs('执行了封锁值设定'.'返回结果：'.$res['message'],'0');
                return $this->error($res['message'],url('System/Systemlocks').'?lid='.$lid);
            }
        }else{
            $lid_list = json_decode(forwarding('lotteryForwarding', '\app\Service\lottery\business\lottery', 'getList', []),true);
            $methodslist = json_decode(forwarding('lotteryForwarding', '\app\Service\lottery\business\methods', 'getLockmethods', ['lid'=>$lid]),true);
            $this->assign('list',$lid_list['data']);
            $this->assign('lid',$lid);
            $this->assign('methodslist',$methodslist['data']);
            return $this->fetch();
        }

    }
}