<?php
/**
 * Created by PhpStorm.
 * User: Jim FAN
 * Date: 2017/6/17
 * Time: 16:00
 */

namespace app\pc\controller;
use app\pc\controller\Base;
use think\Log;

class game extends Base
{
    public $lotteryTypes = array(
        '1' => '时时彩',
        '2' => '11选5',
        '4' => '福彩3D',
        //'5' => 'keno',    //没有任何产品 可暂时屏蔽
        '6' => '快3',
        //'3' => '乐透分区型（蓝红球）',
        '7' => '快乐扑克',
        '8' => 'PK10',
        '9' => '海南七星彩',
        '10' => '香港六合彩',
        '11' => '快乐十分',
    );
    public  function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 投注页面
     */
    public function Play($lid = 2){
        $data = ['test'=>1];
        //1.获取所有彩种
        $res= json_decode(forwarding('lotteryForwarding','\app\Service\lottery\business\lottery','getLot',$data),true);
        $lot_lis = $res['data'];
        $sortLotterys = [];
        foreach ($lot_lis as $v){
            $sortLotterys[] = array('lotteryId' => $v['lid'],
                'name' => $v['name'],
                'cname' => $v['cname'],
                'alink' => strtolower($v['name']),
                'isopened' => 1);
        }
        $this->assign('sortLotterys',json_encode($sortLotterys));
        //2.处理彩种
      $lottery =  $lot_lis[$lid];

      $this->assign('lottery',$lottery);
      $this->assign('minRebateGaps',$lottery['min_rebate_gaps']);
        //得到全包奖金
      $this->assign('maxCombPrize', $lottery['zx_max_comb'] * 2);
        //得到所有玩组法列表及玩法列表和奖金列表
      $mgs = forwarding('lotteryForwarding','\app\Service\lottery\business\method_groups','getMethodGroupsByLid',['lid'=>$lid]);
//      Log::record(json_decode($mgs,true),'error');
      $this->assign('json_methods',$mgs);
        //得到当天已开奖奖期
        if ($lid == 8 && date('Hi') <= '0200') { //对于跨天的在0点以后，应取昨天的$belong_date
            $belong_date = date('Y-m-d', strtotime('-1 day'));
        } else {
            $belong_date = date('Y-m-d');
        }
        $issuelist = json_decode(forwarding('lotteryForwarding','\app\Service\lottery\business\issues','getIssueList',['lid'=>$lid,'amount'=>15,'before_date'=>$belong_date,'status_code'=>2]),true);
        $issues = array();
        $maxOpenissue = 10;
        $tmp = $issuelist['data'];
        foreach ($tmp as $v) {
            $issues[] = array(
                'issue_id' => $v['i_id'],
                'issue' => $v['i_issue'],
                'code' => $v['i_code'],
            );
            $maxOpenissue--;
            if ($maxOpenissue <= 0) {
                break;
            }
        }
        $this->assign('json_openedIssues',json_encode($issues));
        $this->assign('username',session('u_username'));
        return  $this->fetch("./play");
    }

    /**
     * ajax  请求数据页面
     *
     */
    public function ajaxData(){

    }
    /**
     * 获取当前期
     */
    public function getCurIssue(){

    }
    /**
     * //{"code":100000,"data":{"money":"0","siteId":1001,"username":"ceshi777"},"message":"Nomal"}
     *获取余额
     * @return int
     */
    public function showBalance(){

        $arr = [
            "code"=>100000,
            "data"=>["money"=>1000,"siteId"=>1001,"username"=>"ceshi777"],
            "message"=>"Nomal"
        ];
        if (is_array($arr)) {
//            $result['balance'] = cutNum($arr['data']['money']);
            $result['balance'] = number_format($arr['data']['money'], 2);
        }
        return json_encode($result);
    }
}