CREATE TABLE `ffc_order_2_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid2注单临时表';

CREATE TABLE `ffc_order_6_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid6注单临时表';

CREATE TABLE `ffc_order_8_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid8注单临时表';

CREATE TABLE `ffc_order_9_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid9注单临时表';

CREATE TABLE `ffc_order_14_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid14注单临时表';

CREATE TABLE `ffc_order_24_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid24注单临时表';

CREATE TABLE `ffc_order_26_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid26注单临时表';

CREATE TABLE `ffc_order_27_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid27注单临时表';

CREATE TABLE `ffc_order_28_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid28注单临时表';

CREATE TABLE `ffc_order_29_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid29注单临时表';

CREATE TABLE `ffc_order_30_temp` (
	`o_id` BIGINT(20) UNSIGNED NOT NULL  COMMENT '订单ID（打包ID）',
	`o_u_id` INT(8) UNSIGNED NOT NULL COMMENT '用户ID',
	`o_username` VARCHAR(50) NOT NULL COMMENT '用户名',
	`o_top_5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总公司用户名 ',
	`o_top_4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属分公司用户名',
	`o_top_3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属股东用户名',
	`o_top_2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属总代用户名id',
	`o_top_1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属代理用户名',
	`u_proportion_5` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总公司占成',
	`u_proportion_4` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '分公司占成',
	`u_proportion_3` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '股东占成',
	`u_proportion_2` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '总代占成',
	`u_proportion_1` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '代理占成',
	`o_lid` TINYINT(3) UNSIGNED NOT NULL COMMENT '彩种id',
	`o_m_id` int(10) UNSIGNED NOT NULL COMMENT '玩法id',
	`o_mg_id` int(10) UNSIGNED NOT NULL COMMENT '玩法组id',
	`o_issue` CHAR(13) NOT NULL COMMENT '奖期',
	`o_trace_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '追号id 不为0表示追号生成的订单',
	`o_single_num` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总单倍注数',
	`o_multiple` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单倍数',
	`o_modes` ENUM('1','0.5','0.1','0.05','0.01','0.005','0.001','0.0005') NOT NULL DEFAULT '1' COMMENT '元角分',
	`o_amount` DECIMAL(10,4) UNSIGNED NOT NULL COMMENT '本订单总金额',
	`o_prize` DECIMAL(12,4) UNSIGNED NOT NULL DEFAULT '0.0000' COMMENT '总奖金',
	`o_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '下注号码',
	`o_hash_value` CHAR (32) NOT NULL DEFAULT '' COMMENT '加密验证串',
	`o_add_time` DATETIME NOT NULL COMMENT '建立时间',
	`o_check_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '中奖判断状态(0:未判断;1:中奖;2:未中奖)',
	`o_send_prize_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '派奖状态(0:未派奖;1:已派奖)',
	`o_send_prize_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派奖时间',
	`o_cancel_status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否撤单(0未撤单 1用户撤单 2追中撤单 3出号撤单 4未开撤单 9管理员撤单',
	`o_cancel_admin_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '谁撤单',
	`o_cancel_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '撤单时间',
	`o_u_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '用户ip',
	`o_deleteflag`  TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删 0否 1是',
	`o_proxy_ip` CHAR(15) NOT NULL DEFAULT '0.0.0.0' COMMENT '前端服务器ip',
	`o_server_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '从哪台机器来的',
	`o_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	PRIMARY KEY (`o_id`),
	INDEX `o_lid` (`o_lid`, `o_issue`),
	INDEX `o_add_time` (`o_add_time`),
	INDEX `o_u_id` (`o_u_id`),
	INDEX `o_trace_id` (`o_trace_id`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='lid30注单临时表';

